### ISSUE TITLE
Build failure with Lua 5.1

### ISSUE THREAD

**Issue by Arfrever** [libpinyin/ibus-libpinyin#89]
ibus-libpinyin (at least 1.9.0 and 1.9.1) fails to build with Lua 5.1:
```
/bin/sh ../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc -pthread -I/usr/include/ibus-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -o lua-ext-console lua_ext_console-lua-ext-console.o libpylua.la  
libtool: link: x86_64-pc-linux-gnu-gcc -pthread -I/usr/include/ibus-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -o lua-ext-console lua_ext_console-lua-ext-console.o  -Wl,--as-needed ./.libs/libpylua.a -libus-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 /usr/lib64//liblua.so -ldl -lm -pthread -Wl,-rpath -Wl,/usr/lib64/ -Wl,-rpath -Wl,/usr/lib64/
./.libs/libpylua.a(libpylua_la-lua-plugin.o): In function `ibus_engine_plugin_get_retvals':
lua-plugin.c:(.text+0x9d7): undefined reference to `lua_rawlen'
./.libs/libpylua.a(libpylua_la-lua-plugin.o): In function `ibus_engine_plugin_call':
lua-plugin.c:(.text+0x85e): undefined reference to `lua_rawlen'
./.libs/libpylua.a(libpylua_la-lua-plugin-init.o): In function `ime_register_trigger':
lua-plugin-init.c:(.text+0x489): undefined reference to `lua_rawlen'
lua-plugin-init.c:(.text+0x525): undefined reference to `lua_rawlen'
./.libs/libpylua.a(libpylua_la-lua-plugin-init.o): In function `ime_join_string':
lua-plugin-init.c:(.text+0x883): undefined reference to `lua_rawlen'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:733: lua-ext-console] Error 1
```

Lua documentation says that in Lua 5.2 `lua_objlen` function was renamed to `lua_rawlen`.

`lua/lua-plugin.c` and `lua/lua-plugin-init.c` files contain:
```
#ifndef lua_objlen
#define lua_objlen lua_rawlen
#endif
```
In Lua 5.1, `lua_objlen` exists, but is not a preprocessor macro, so `#ifndef lua_objlen` evaluates to true.

**Comment by epico** [comment]
Thanks for the report! :)

Do I need to change the code like below?

#if LUA_VERSION_NUM >= 502

#define lua_open luaL_newstate
#define lua_objlen lua_rawlen

#endif

**Comment by epico** [comment]
Sorry, please try the below patch:
https://gist.github.com/epico/8629a6124991036199cc787a7864ebb7

**Comment by Arfrever** [comment]
Patch works.
That internal `#ifndef lua_objlen` can be dropped, since it is always evaluated as true.
```
#if LUA_VERSION_NUM >= 502
#define lua_objlen lua_rawlen
#endif
```

**Comment by epico** [comment]
No, without #ifndef lua_objlen, it will cause warning on Lua 5.3.

In Lua 5.3, it has the following definition:
#define lua_objlen(L,i)  lua_rawlen(L, (i))

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/53b5d4de6c8732da113f56efdd1e0e9b797d8591 .

Could you review the code?

**Comment by epico** [comment]
ibus-libpinyin 1.9.2 released, close issue.
